import { useState, useEffect, useRef } from "react";
import { Chart, registerables } from "chart.js";
Chart.register(...registerables);

const API = "http://localhost:5000/api";
const C = {
  teal:"#2DD4BF",amber:"#F59E0B",rose:"#FB7185",indigo:"#818CF8",
  violet:"#A78BFA",emerald:"#34D399",sky:"#38BDF8",orange:"#FB923C",
  bg:"#0F172A",card:"#1E293B",cardHover:"#243044",
  border:"#334155",text:"#F1F5F9",textMuted:"#94A3B8",
};
const CD={responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:C.textMuted,font:{family:"'DM Sans',sans-serif",size:11},boxWidth:10,padding:12}},tooltip:{backgroundColor:"#1E293B",borderColor:C.border,borderWidth:1,titleColor:C.text,bodyColor:C.textMuted,padding:10,cornerRadius:8}},scales:{x:{ticks:{color:C.textMuted,font:{family:"'DM Sans',sans-serif",size:10}},grid:{color:"rgba(51,65,85,0.4)"}},y:{ticks:{color:C.textMuted,font:{family:"'DM Sans',sans-serif",size:10}},grid:{color:"rgba(51,65,85,0.4)"}}}};

const M={
  schoolYears:[{SchoolYearKey:2,YearLabel:"2019/2020",IsCurrent:0},{SchoolYearKey:3,YearLabel:"2020/2021",IsCurrent:0},{SchoolYearKey:4,YearLabel:"2021/2022",IsCurrent:0},{SchoolYearKey:5,YearLabel:"2022/2023",IsCurrent:0},{SchoolYearKey:6,YearLabel:"2023/2024",IsCurrent:0},{SchoolYearKey:7,YearLabel:"2024/2025",IsCurrent:1}],
  axis1Kpis:{total_students:1578,avg_score:11.4,pass_rate:63.2,fail_rate:36.8,max_score:20,min_score:0},
  avgBySubject:[{subject:"Mathematics",avg_score:12.3,pass_rate:68,pass_count:668,fail_count:312,n_evaluations:980},{subject:"Physics",avg_score:11.8,pass_rate:64,pass_count:557,fail_count:313,n_evaluations:870},{subject:"French",avg_score:13.1,pass_rate:72,pass_count:662,fail_count:258,n_evaluations:920},{subject:"Arabic",avg_score:14.2,pass_rate:80,pass_count:760,fail_count:190,n_evaluations:950},{subject:"English",avg_score:12.7,pass_rate:70,pass_count:602,fail_count:258,n_evaluations:860},{subject:"History",avg_score:11.2,pass_rate:61,pass_count:488,fail_count:312,n_evaluations:800},{subject:"Biology",avg_score:10.9,pass_rate:58,pass_count:452,fail_count:328,n_evaluations:780},{subject:"Chemistry",avg_score:10.4,pass_rate:54,pass_count:410,fail_count:350,n_evaluations:760},{subject:"Philosophy",avg_score:13.5,pass_rate:75,pass_count:615,fail_count:205,n_evaluations:820},{subject:"Sport",avg_score:15.8,pass_rate:92,pass_count:874,fail_count:76,n_evaluations:950}],
  scoreDist:[{bin:"0-2",count:42},{bin:"2-4",count:98},{bin:"4-6",count:187},{bin:"6-8",count:312},{bin:"8-10",count:445},{bin:"10-12",count:623},{bin:"12-14",count:538},{bin:"14-16",count:398},{bin:"16-18",count:210},{bin:"18-20",count:87}],
  avgByYear:[{year_label:"2019/20",avg_score:10.8,pass_rate:58,student_count:1200},{year_label:"2020/21",avg_score:11.1,pass_rate:60,student_count:1320},{year_label:"2021/22",avg_score:11.6,pass_rate:63,student_count:1420},{year_label:"2022/23",avg_score:12.0,pass_rate:66,student_count:1490},{year_label:"2023/24",avg_score:11.4,pass_rate:62,student_count:1530},{year_label:"2024/25",avg_score:11.9,pass_rate:65,student_count:1578}],
  axis3Kpis:{students_tracked:1578,presence_rate:87.3,late_rate:4.2,total_records:61,teachers_tracked:109,avg_hours:4.8,teacher_late_rate:2.1},
  absenceByMonth:[{month:9,month_name:"Sep",year:2024,absence_rate:3.2},{month:10,month_name:"Oct",year:2024,absence_rate:4.1},{month:11,month_name:"Nov",year:2024,absence_rate:5.8},{month:12,month_name:"Dec",year:2024,absence_rate:7.2},{month:1,month_name:"Jan",year:2025,absence_rate:6.4},{month:2,month_name:"Feb",year:2025,absence_rate:4.9},{month:3,month_name:"Mar",year:2025,absence_rate:5.3},{month:4,month_name:"Apr",year:2025,absence_rate:4.0},{month:5,month_name:"May",year:2025,absence_rate:3.8}],
  teacherHours:[{month_name:"Sep",year:2024,total_hours:820,avg_hours_per_teacher:8.4},{month_name:"Oct",year:2024,total_hours:1240,avg_hours_per_teacher:12.2},{month_name:"Nov",year:2024,total_hours:1180,avg_hours_per_teacher:11.2},{month_name:"Dec",year:2024,total_hours:960,avg_hours_per_teacher:9.6},{month_name:"Jan",year:2025,total_hours:1100,avg_hours_per_teacher:10.6},{month_name:"Feb",year:2025,total_hours:1080,avg_hours_per_teacher:10.5},{month_name:"Mar",year:2025,total_hours:1160,avg_hours_per_teacher:10.9},{month_name:"Apr",year:2025,total_hours:1020,avg_hours_per_teacher:10.1},{month_name:"May",year:2025,total_hours:940,avg_hours_per_teacher:9.5}],
  topAbsent:[{student_name:"Ahmed Mansour",total_days:20,absent_days:9,absence_rate:45.0},{student_name:"Leila Bouhajeb",total_days:18,absent_days:7,absence_rate:38.9},{student_name:"Youssef Kraiem",total_days:22,absent_days:8,absence_rate:36.4},{student_name:"Mariem Jaziri",total_days:16,absent_days:5,absence_rate:31.3},{student_name:"Sami Ben Salah",total_days:24,absent_days:7,absence_rate:29.2},{student_name:"Hana Trabelsi",total_days:20,absent_days:5,absence_rate:25.0},{student_name:"Omar Chaabane",total_days:18,absent_days:4,absence_rate:22.2},{student_name:"Ines Khelifi",total_days:22,absent_days:4,absence_rate:18.2}],
  attVsScore:Array.from({length:35},(_,i)=>({student_name:`Student ${i+1}`,absence_rate:Math.max(0,Math.min(48,4+Math.random()*40)),avg_score:Math.max(4,Math.min(20,15.5-(Math.random()*0.25*(i%16))+Math.random()*2.5))})),
  progression:[{year_label:"2019/20",avg_score:9.8,count:1},{year_label:"2020/21",avg_score:10.5,count:1},{year_label:"2021/22",avg_score:11.2,count:1},{year_label:"2022/23",avg_score:12.1,count:1},{year_label:"2023/24",avg_score:11.6,count:1},{year_label:"2024/25",avg_score:12.4,count:1}],
  stability:[{student_name:"Ali Ben Youssef",avg_score:14.2,score_stddev:0.8,years_active:5},{student_name:"Sana Mrad",avg_score:12.8,score_stddev:1.1,years_active:4},{student_name:"Karim Abidi",avg_score:11.5,score_stddev:1.4,years_active:4},{student_name:"Nour Hamdi",avg_score:13.1,score_stddev:1.7,years_active:5},{student_name:"Bilel Chaari",avg_score:10.2,score_stddev:2.3,years_active:3},{student_name:"Rania Ben Ali",avg_score:9.8,score_stddev:2.9,years_active:4},{student_name:"Oussama Krid",avg_score:8.4,score_stddev:3.4,years_active:3}],
  regression:[{student_name:"Mohamed Slim",historical_avg:13.2,latest_avg:9.8,delta:-3.4,trend_label:"Regression"},{student_name:"Azza Mhenni",historical_avg:11.8,latest_avg:8.7,delta:-3.1,trend_label:"Regression"},{student_name:"Wael Dridi",historical_avg:12.1,latest_avg:9.5,delta:-2.6,trend_label:"Regression"},{student_name:"Fares Jebali",historical_avg:9.8,latest_avg:12.3,delta:2.5,trend_label:"Improvement"},{student_name:"Amira Souissi",historical_avg:10.1,latest_avg:13.4,delta:3.3,trend_label:"Improvement"},{student_name:"Tarek Belhaj",historical_avg:11.2,latest_avg:11.5,delta:0.3,trend_label:"Stable"}],
  semester:[{year_label:"2023/24",report_name:"Semester 1",avg_score:11.2},{year_label:"2023/24",report_name:"Semester 2",avg_score:11.8},{year_label:"2024/25",report_name:"Semester 1",avg_score:11.6}],
  weatherVsAbsence:[{full_date:"2024-09-02",absence_rate:2.1,precipitation_mm:0,is_rainy:false},{full_date:"2024-10-07",absence_rate:4.8,precipitation_mm:8.2,is_rainy:true},{full_date:"2024-11-04",absence_rate:6.2,precipitation_mm:15.4,is_rainy:true},{full_date:"2024-11-11",absence_rate:7.1,precipitation_mm:22.1,is_rainy:true},{full_date:"2024-12-02",absence_rate:5.8,precipitation_mm:11.3,is_rainy:true},{full_date:"2025-01-06",absence_rate:6.4,precipitation_mm:18.7,is_rainy:true},{full_date:"2025-02-03",absence_rate:4.2,precipitation_mm:2.1,is_rainy:false},{full_date:"2025-03-03",absence_rate:4.9,precipitation_mm:6.8,is_rainy:true},{full_date:"2025-04-07",absence_rate:3.8,precipitation_mm:0,is_rainy:false}],
  rainyVsDry:{rainy_avg:6.1,n_rainy:6,dry_avg:3.2,n_dry:3},
  seasonal:[{month:9,month_name:"Sep",absence_rate:3.2,avg_precipitation:0.4},{month:10,month_name:"Oct",absence_rate:4.8,avg_precipitation:4.1},{month:11,month_name:"Nov",absence_rate:6.4,avg_precipitation:12.3},{month:12,month_name:"Dec",absence_rate:7.2,avg_precipitation:9.8},{month:1,month_name:"Jan",absence_rate:6.8,avg_precipitation:14.2},{month:2,month_name:"Feb",absence_rate:4.9,avg_precipitation:8.1},{month:3,month_name:"Mar",absence_rate:5.3,avg_precipitation:6.4},{month:4,month_name:"Apr",absence_rate:4.0,avg_precipitation:2.3},{month:5,month_name:"May",absence_rate:3.8,avg_precipitation:0.8}],
  outcomesByReport:[{report_name:"Sem 1",subject:"Mathematics",year_label:"2024/25",avg_score:11.2,score_stddev:3.1,student_count:285,pass_rate:61},{report_name:"Sem 2",subject:"Mathematics",year_label:"2024/25",avg_score:12.4,score_stddev:2.8,student_count:280,pass_rate:68}],
  dispersion:[{report_name:"Sem 1 Eval",score_min:1.0,score_max:19.5,score_avg:11.2,score_stddev:3.1,n:820},{report_name:"Sem 2 Eval",score_min:2.0,score_max:20.0,score_avg:12.1,score_stddev:2.9,n:810},{report_name:"End-of-Year",score_min:3.5,score_max:19.0,score_avg:11.8,score_stddev:2.7,n:790}],
  presencePerf:[{report_name:"Sem 1 Eval",avg_score:11.2,presence_rate:86.4},{report_name:"Sem 2 Eval",avg_score:12.1,presence_rate:88.2},{report_name:"End-of-Year",avg_score:11.8,presence_rate:87.0}],
  subjectList:[{subject:"Mathematics"},{subject:"Physics"},{subject:"French"},{subject:"Arabic"},{subject:"English"},{subject:"History"},{subject:"Biology"},{subject:"Chemistry"},{subject:"Philosophy"},{subject:"Sport"}],
  riskScores:[{student_name:"Ahmed Mansour",avg_score:7.2,absence_rate:45.0,fail_rate_pct:78,risk_score:82.4,risk_level:"High"},{student_name:"Leila Bouhajeb",avg_score:8.1,absence_rate:38.9,fail_rate_pct:65,risk_score:74.2,risk_level:"High"},{student_name:"Youssef Kraiem",avg_score:7.8,absence_rate:36.4,fail_rate_pct:70,risk_score:72.1,risk_level:"High"},{student_name:"Mariem Jaziri",avg_score:8.9,absence_rate:31.3,fail_rate_pct:58,risk_score:64.3,risk_level:"High"},{student_name:"Sami Ben Salah",avg_score:9.5,absence_rate:29.2,fail_rate_pct:52,risk_score:57.8,risk_level:"Medium"},{student_name:"Hana Trabelsi",avg_score:9.8,absence_rate:25.0,fail_rate_pct:46,risk_score:51.2,risk_level:"Medium"},{student_name:"Omar Chaabane",avg_score:10.2,absence_rate:22.2,fail_rate_pct:38,risk_score:42.6,risk_level:"Medium"},{student_name:"Ines Khelifi",avg_score:11.4,absence_rate:18.2,fail_rate_pct:28,risk_score:28.1,risk_level:"Low"},{student_name:"Nizar Hamdi",avg_score:12.1,absence_rate:15.0,fail_rate_pct:22,risk_score:20.4,risk_level:"Low"},{student_name:"Rania Mrabet",avg_score:13.2,absence_rate:12.5,fail_rate_pct:15,risk_score:12.8,risk_level:"Low"}],
  riskDist:[{risk_level:"High",student_count:48,avg_score:7.9,avg_absence_rate:38.2},{risk_level:"Medium",student_count:183,avg_score:9.6,avg_absence_rate:22.8},{risk_level:"Low",student_count:1347,avg_score:12.8,avg_absence_rate:7.4}],
  earlyWarning:[{student_name:"Ahmed Mansour",avg_score:7.2,absence_rate:45.0,fail_rate_pct:78,flag_low_score:1,flag_high_absence:1,flag_high_fail_rate:1,warning_count:3},{student_name:"Leila Bouhajeb",avg_score:8.1,absence_rate:38.9,fail_rate_pct:65,flag_low_score:1,flag_high_absence:1,flag_high_fail_rate:1,warning_count:3},{student_name:"Sami Ben Salah",avg_score:9.5,absence_rate:29.2,fail_rate_pct:52,flag_low_score:1,flag_high_absence:1,flag_high_fail_rate:1,warning_count:3},{student_name:"Hana Trabelsi",avg_score:9.8,absence_rate:25.0,fail_rate_pct:46,flag_low_score:1,flag_high_absence:1,flag_high_fail_rate:0,warning_count:2}],
  zones:[{zone_name:"Sahloul",student_count:342,absence_rate:5.2,late_rate:2.1,avg_score:12.4},{zone_name:"Khezama",student_count:287,absence_rate:6.8,late_rate:3.2,avg_score:11.2},{zone_name:"Erriadh",student_count:198,absence_rate:8.1,late_rate:4.5,avg_score:10.8},{zone_name:"Kalaa",student_count:156,absence_rate:4.2,late_rate:1.8,avg_score:13.1}],
  periodTypes:[{period_type:"pre_holiday",period_label:"Before Holiday",avg_absence_rate:8.5,n_days:45},{period_type:"post_holiday",period_label:"After Holiday",avg_absence_rate:6.2,n_days:45},{period_type:"pre_exam",period_label:"Before Exams",avg_absence_rate:4.8,n_days:30},{period_type:"exam",period_label:"Exam Period",avg_absence_rate:3.2,n_days:40},{period_type:"normal",period_label:"Normal Days",avg_absence_rate:4.1,n_days:120}],
  schools:[{school_name:"SLS Leaders School",student_count:234,avg_score:13.2,pass_rate:78,absence_rate:3.8},{school_name:"Allama",student_count:198,avg_score:12.8,pass_rate:74,absence_rate:4.2},{school_name:"Avicenne / Ibn Sina",student_count:167,avg_score:12.1,pass_rate:70,absence_rate:5.1},{school_name:"Amad",student_count:98,avg_score:11.8,pass_rate:67,absence_rate:5.8},{school_name:"Select School",student_count:87,avg_score:12.4,pass_rate:71,absence_rate:4.9},{school_name:"Les Élites / AKC",student_count:76,avg_score:11.5,pass_rate:64,absence_rate:6.2},{school_name:"Marie Curie",student_count:65,avg_score:13.0,pass_rate:76,absence_rate:4.1},{school_name:"Other / Unknown",student_count:653,avg_score:11.1,pass_rate:60,absence_rate:7.2}],
};

async function apiFetch(path, mk) {
  try {
    const r = await fetch(`${API}${path}`);
    if (!r.ok) throw 0;
    const data = await r.json();
    // Normalize school-years response to always use SchoolYearKey / YearLabel / IsCurrent
    if (mk === "schoolYears" && Array.isArray(data)) {
      return data.map(y => ({
        SchoolYearKey: y.SchoolYearKey ?? y.id ?? y.school_year_key,
        YearLabel: y.YearLabel ?? y.name ?? y.Description ?? y.year_label,
        IsCurrent: y.IsCurrent ?? y.isCurrent ?? 0,
      }));
    }
    return data;
  } catch {
    return M[mk];
  }
}

function useChart(ref, cfg) {
  useEffect(() => {
    if (!ref.current) return;
    const c = new Chart(ref.current.getContext("2d"), cfg);
    return () => c.destroy();
  }, [JSON.stringify(cfg)]);
}

// ── Shared UI primitives ─────────────────────────────────────────────────────
function KpiCard({label,value,unit="",sub,color=C.teal}){return(<div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:"18px 20px",borderTop:`3px solid ${color}`}}><div style={{fontSize:11,color:C.textMuted,textTransform:"uppercase",letterSpacing:"0.08em"}}>{label}</div><div style={{display:"flex",alignItems:"baseline",gap:4,marginTop:6}}><span style={{fontSize:28,fontWeight:700,color,fontFamily:"'Space Mono',monospace",letterSpacing:"-1px"}}>{typeof value==="number"?value.toLocaleString("fr-TN",{maximumFractionDigits:1}):(value??"—")}</span>{unit&&<span style={{fontSize:13,color:C.textMuted}}>{unit}</span>}</div>{sub&&<div style={{fontSize:11,color:C.textMuted,marginTop:2}}>{sub}</div>}</div>);}
function CC({title,subtitle,children,height=250}){return(<div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:"18px 20px",display:"flex",flexDirection:"column",gap:12}}><div><div style={{fontSize:13,fontWeight:600,color:C.text}}>{title}</div>{subtitle&&<div style={{fontSize:11,color:C.textMuted,marginTop:2}}>{subtitle}</div>}</div><div style={{height,position:"relative"}}>{children}</div></div>);}
function SH({axis,title,desc,color=C.teal}){return(<div style={{display:"flex",alignItems:"center",gap:14,marginBottom:20,paddingBottom:14,borderBottom:`1px solid ${C.border}`}}><div style={{width:42,height:42,borderRadius:10,background:`${color}18`,border:`1px solid ${color}40`,display:"flex",alignItems:"center",justifyContent:"center",fontFamily:"'Space Mono',monospace",fontSize:11,fontWeight:700,color,flexShrink:0}}>{axis}</div><div><div style={{fontSize:18,fontWeight:700,color:C.text}}>{title}</div><div style={{fontSize:12,color:C.textMuted,marginTop:2}}>{desc}</div></div></div>);}
function IS({items,color}){return(<div style={{background:`${color}0F`,border:`1px solid ${color}30`,borderRadius:12,padding:"14px 18px",display:"flex",gap:28,flexWrap:"wrap"}}>{items.map(({label,value})=>(<div key={label}><div style={{fontSize:10,color:C.textMuted,textTransform:"uppercase",letterSpacing:"0.07em"}}>{label}</div><div style={{fontSize:13,fontWeight:600,color,marginTop:2,fontFamily:"'Space Mono',monospace"}}>{value??"—"}</div></div>))}</div>);}
function RB({level}){const m={High:[C.rose,"#3B0A14"],Medium:[C.amber,"#2D1A00"],Low:[C.teal,"#003330"]};const[fg,bg]=m[level]||[C.textMuted,C.card];return <span style={{background:bg,color:fg,border:`1px solid ${fg}40`,borderRadius:20,padding:"2px 10px",fontSize:11,fontWeight:600}}>{level}</span>;}

// ── Axis 1 — Academic Performance ────────────────────────────────────────────
function Axis1({qs}){
  const[kpi,setKpi]=useState(null);const[subj,setSubj]=useState([]);const[dist,setDist]=useState([]);const[byY,setByY]=useState([]);
  useEffect(()=>{Promise.all([apiFetch(`/axis1/kpis${qs}`,"axis1Kpis"),apiFetch(`/axis1/avg-by-subject${qs}`,"avgBySubject"),apiFetch(`/axis1/score-distribution${qs}`,"scoreDist"),apiFetch(`/axis1/avg-by-school-year`,"avgByYear"),apiFetch(`/axis1/pass-fail-by-subject${qs}`,"avgBySubject")]).then(([k,s,d,y])=>{setKpi(k);setSubj(s);setDist(d);setByY(y);});},[qs]);
  const r1=useRef(),r2=useRef(),r3=useRef(),r4=useRef();
  const tot=dist.reduce((s,d)=>s+d.count,0);
  useChart(r1,{type:"bar",data:{labels:subj.map(d=>(d.subject||"").slice(0,9)+"…"),datasets:[{label:"Avg",data:subj.map(d=>d.avg_score),backgroundColor:subj.map(d=>d.avg_score>=12?`${C.teal}CC`:d.avg_score>=10?`${C.amber}CC`:`${C.rose}CC`),borderWidth:0,borderRadius:5}]},options:{...CD,plugins:{...CD.plugins,legend:{display:false}},scales:{x:{...CD.scales.x},y:{...CD.scales.y,min:0,max:20}}}});
  useChart(r2,{type:"bar",data:{labels:dist.map(d=>d.bin),datasets:[{label:"Students",data:dist.map(d=>d.count),backgroundColor:dist.map(d=>{const m=(parseFloat(d.bin.split("-")[0])+parseFloat(d.bin.split("-")[1]))/2;return m<10?`${C.rose}BB`:m<14?`${C.amber}BB`:`${C.teal}BB`;}),borderWidth:0,borderRadius:4}]},options:{...CD,plugins:{...CD.plugins,legend:{display:false},tooltip:{...CD.plugins.tooltip,callbacks:{label:ctx=>` ${ctx.parsed.y} (${((ctx.parsed.y/tot)*100).toFixed(1)}%)`}}},scales:{x:{...CD.scales.x},y:{...CD.scales.y}}}});
  useChart(r3,{type:"line",data:{labels:byY.map(d=>d.year_label),datasets:[{label:"Avg score",data:byY.map(d=>d.avg_score),borderColor:C.teal,backgroundColor:`${C.teal}18`,tension:0.35,fill:true,pointBackgroundColor:C.teal,pointRadius:4,yAxisID:"y"},{label:"Pass %",data:byY.map(d=>d.pass_rate),borderColor:C.amber,backgroundColor:"transparent",tension:0.35,borderDash:[5,3],pointBackgroundColor:C.amber,pointRadius:3,yAxisID:"y2"}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,min:0,max:20,position:"left"},y2:{...CD.scales.y,min:0,max:100,position:"right",grid:{drawOnChartArea:false}}}}});
  useChart(r4,{type:"bar",data:{labels:subj.slice(0,8).map(d=>(d.subject||"").slice(0,10)),datasets:[{label:"Pass",data:subj.slice(0,8).map(d=>d.pass_count||Math.round((d.n_evaluations||500)*d.pass_rate/100)),backgroundColor:`${C.teal}CC`,borderRadius:4,stack:"s"},{label:"Fail",data:subj.slice(0,8).map(d=>d.fail_count||Math.round((d.n_evaluations||500)*(1-d.pass_rate/100))),backgroundColor:`${C.rose}CC`,borderRadius:4,stack:"s"}]},options:{...CD,scales:{x:{...CD.scales.x,stacked:true},y:{...CD.scales.y,stacked:true}}}});
  if(!kpi)return null;
  return(<div style={{display:"flex",flexDirection:"column",gap:22}}><SH axis="A1" title="Academic Performance Analysis" desc="Average grades · score distribution · pass/fail rates · year-over-year comparison" color={C.teal}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><KpiCard label="Total students" value={kpi.total_students} color={C.teal}/><KpiCard label="Average score" value={kpi.avg_score} unit="/20" color={C.indigo}/><KpiCard label="Pass rate" value={kpi.pass_rate} unit="%" sub="Score ≥ 10/20" color={C.amber}/><KpiCard label="Fail rate" value={kpi.fail_rate} unit="%" sub="Score < 10/20" color={C.rose}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><CC title="Average score by subject" subtitle="Teal ≥ 12 · amber 10–12 · rose < 10" height={240}><canvas ref={r1}/></CC><CC title="Score distribution" subtitle="Students per score interval" height={240}><canvas ref={r2}/></CC></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><CC title="Performance across school years" subtitle="Avg score (left) vs pass rate % (right)" height={240}><canvas ref={r3}/></CC><CC title="Pass vs fail by subject" subtitle="Stacked count per subject" height={240}><canvas ref={r4}/></CC></div><IS color={C.teal} items={[{label:"Best subject",value:subj[0]?.subject},{label:"Weakest subject",value:subj[subj.length-1]?.subject},{label:"Score range",value:`${kpi.min_score} – ${kpi.max_score} / 20`},{label:"Pass/fail split",value:`${kpi.pass_rate}% / ${kpi.fail_rate}%`}]}/></div>);
}

// ── Axis 2 — Temporal Trends ─────────────────────────────────────────────────
function Axis2({qs}){
  const[prog,setProg]=useState([]);const[stab,setStab]=useState([]);const[regr,setRegr]=useState([]);const[sem,setSem]=useState([]);
  useEffect(()=>{Promise.all([apiFetch(`/axis2/progression-by-student${qs}`,"progression"),apiFetch(`/axis2/stability-index`,"stability"),apiFetch(`/axis2/regression-detection`,"regression"),apiFetch(`/axis2/semester-comparison`,"semester")]).then(([p,s,r,sm])=>{setProg(p);setStab(s);setRegr(r);setSem(sm);});},[qs]);
  const r1=useRef(),r2=useRef(),r3=useRef();
  const byY=Object.values(prog.reduce((a,r)=>{const k=r.year_label;if(!a[k])a[k]={year_label:k,total:0,count:0};a[k].total+=r.avg_score;a[k].count++;return a;},{})).sort((a,b)=>a.year_label.localeCompare(b.year_label));
  useChart(r1,{type:"line",data:{labels:byY.map(d=>d.year_label),datasets:[{label:"Avg score",data:byY.map(d=>+(d.total/d.count).toFixed(2)),borderColor:C.violet,backgroundColor:`${C.violet}18`,tension:0.4,fill:true,pointBackgroundColor:C.violet,pointRadius:5}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,min:0,max:20}}}});
  useChart(r2,{type:"bar",data:{labels:stab.map(d=>d.student_name.split(" ")[0]),datasets:[{label:"Avg score",data:stab.map(d=>d.avg_score),backgroundColor:`${C.sky}BB`,borderRadius:4,yAxisID:"y"},{label:"Std dev",data:stab.map(d=>d.score_stddev),backgroundColor:`${C.orange}BB`,borderRadius:4,yAxisID:"y2"}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,position:"left",max:20},y2:{...CD.scales.y,position:"right",grid:{drawOnChartArea:false},title:{display:true,text:"Std dev",color:C.textMuted}}}}});
  const sorted=[...regr].sort((a,b)=>a.delta-b.delta);
  useChart(r3,{type:"bar",data:{labels:sorted.map(d=>d.student_name.split(" ")[0]),datasets:[{label:"Score delta",data:sorted.map(d=>d.delta),backgroundColor:sorted.map(d=>d.delta<0?`${C.rose}CC`:`${C.emerald}CC`),borderWidth:0,borderRadius:4}]},options:{indexAxis:"y",...CD,plugins:{...CD.plugins,legend:{display:false}},scales:{x:{...CD.scales.x,title:{display:true,text:"Score delta",color:C.textMuted}},y:{...CD.scales.y}}}});
  return(<div style={{display:"flex",flexDirection:"column",gap:22}}><SH axis="A2" title="Temporal Progression & Trends" desc="Score progression · stability index · regression detection · semester comparison" color={C.violet}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><KpiCard label="Years tracked" value={byY.length} color={C.violet}/><KpiCard label="Improving" value={regr.filter(r=>r.trend_label==="Improvement").length} color={C.emerald}/><KpiCard label="Regressing" value={regr.filter(r=>r.trend_label==="Regression").length} color={C.rose}/><KpiCard label="Stable profiles" value={stab.filter(s=>s.score_stddev<1.5).length} color={C.sky} sub="Std dev < 1.5"/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><CC title="Average score progression over years" subtitle="Aggregated across all students" height={240}><canvas ref={r1}/></CC><CC title="Performance stability index" subtitle="Blue: avg score · Orange: std deviation" height={240}><canvas ref={r2}/></CC></div><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:16}}><CC title="Regression & improvement detection" subtitle="Delta = latest − historical avg · rose=regression · green=improvement" height={280}><canvas ref={r3}/></CC><CC title="Semester breakdown" subtitle="Avg score per period" height={280}><div style={{overflowY:"auto",height:"100%"}}>{sem.map((s,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:`1px solid ${C.border}`}}><div><div style={{fontSize:12,fontWeight:600,color:C.text}}>{s.report_name}</div><div style={{fontSize:11,color:C.textMuted}}>{s.year_label}</div></div><span style={{fontFamily:"'Space Mono',monospace",fontSize:14,fontWeight:700,color:s.avg_score>=12?C.teal:s.avg_score>=10?C.amber:C.rose}}>{s.avg_score?.toFixed(1)}<span style={{fontSize:10,color:C.textMuted}}>/20</span></span></div>))}</div></CC></div><IS color={C.violet} items={[{label:"Most stable",value:stab[0]?.student_name},{label:"Biggest regression",value:regr.find(r=>r.trend_label==="Regression")?.student_name},{label:"Biggest improvement",value:regr.find(r=>r.trend_label==="Improvement")?.student_name},{label:"Avg std dev",value:stab.length?(stab.reduce((s,r)=>s+r.score_stddev,0)/stab.length).toFixed(2)+" pts":"—"}]}/></div>);
}

// ── Axis 3 — Attendance ──────────────────────────────────────────────────────
function Axis3({qs}){
  const[kpi,setKpi]=useState(null);const[absMon,setAbsMon]=useState([]);const[tchHrs,setTchHrs]=useState([]);const[topAbs,setTopAbs]=useState([]);const[sc,setSc]=useState([]);
  useEffect(()=>{Promise.all([apiFetch(`/axis3/kpis${qs}`,"axis3Kpis"),apiFetch(`/axis3/absence-rate-by-month${qs}`,"absenceByMonth"),apiFetch(`/axis3/teacher-hours-by-month${qs}`,"teacherHours"),apiFetch(`/axis3/top-absent-students${qs}`,"topAbsent"),apiFetch(`/axis3/attendance-vs-score${qs}`,"attVsScore")]).then(([k,a,t,ta,s])=>{setKpi(k);setAbsMon(a);setTchHrs(t);setTopAbs(ta);setSc(s);});},[qs]);
  const r1=useRef(),r2=useRef(),r3=useRef(),r4=useRef();
  useChart(r1,{type:"line",data:{labels:absMon.map(d=>d.month_name),datasets:[{label:"Absence %",data:absMon.map(d=>d.absence_rate),borderColor:C.rose,backgroundColor:`${C.rose}18`,tension:0.4,fill:true,pointBackgroundColor:C.rose,pointRadius:4}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,min:0,ticks:{...CD.scales.y.ticks,callback:v=>`${v}%`}}}}});
  useChart(r2,{type:"bar",data:{labels:tchHrs.map(d=>d.month_name),datasets:[{label:"Total hours",data:tchHrs.map(d=>d.total_hours),backgroundColor:`${C.indigo}BB`,borderRadius:5,yAxisID:"y"},{label:"Avg/teacher",data:tchHrs.map(d=>d.avg_hours_per_teacher),backgroundColor:`${C.teal}BB`,borderRadius:5,yAxisID:"y2"}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,position:"left"},y2:{...CD.scales.y,position:"right",grid:{drawOnChartArea:false}}}}});
  useChart(r3,{type:"bar",data:{labels:topAbs.map(d=>d.student_name.split(" ")[0]),datasets:[{label:"Absence %",data:topAbs.map(d=>d.absence_rate),backgroundColor:topAbs.map(d=>d.absence_rate>=35?`${C.rose}CC`:d.absence_rate>=20?`${C.amber}CC`:`${C.teal}CC`),borderWidth:0,borderRadius:5}]},options:{indexAxis:"y",...CD,plugins:{...CD.plugins,legend:{display:false}},scales:{x:{...CD.scales.x,min:0,max:100,ticks:{...CD.scales.x.ticks,callback:v=>`${v}%`}},y:{...CD.scales.y}}}});
  useChart(r4,{type:"scatter",data:{datasets:[{data:sc.map(d=>({x:d.absence_rate,y:d.avg_score,name:d.student_name})),backgroundColor:sc.map(d=>d.avg_score<10&&d.absence_rate>20?`${C.rose}CC`:d.avg_score>=14?`${C.teal}CC`:`${C.amber}88`),pointRadius:5}]},options:{...CD,plugins:{...CD.plugins,legend:{display:false},tooltip:{...CD.plugins.tooltip,callbacks:{label:ctx=>[ctx.raw.name,`Absence: ${ctx.raw.x?.toFixed(1)}%`,`Score: ${ctx.raw.y?.toFixed(2)}/20`]}}},scales:{x:{...CD.scales.x,title:{display:true,text:"Absence rate (%)",color:C.textMuted}},y:{...CD.scales.y,min:0,max:20,title:{display:true,text:"Avg score /20",color:C.textMuted}}}}});
  if(!kpi)return null;
  return(<div style={{display:"flex",flexDirection:"column",gap:22}}><SH axis="A3" title="Attendance & Engagement" desc="Absence rates · teacher hours · chronic absenteeism · attendance–performance correlation" color={C.rose}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><KpiCard label="Presence rate" value={kpi.presence_rate} unit="%" sub={`${kpi.students_tracked} students`} color={C.teal}/><KpiCard label="Absence rate" value={(100-kpi.presence_rate).toFixed(1)} unit="%" color={C.rose}/><KpiCard label="Late arrivals" value={kpi.late_rate} unit="%" sub="Student punctuality" color={C.amber}/><KpiCard label="Avg teacher hrs" value={kpi.avg_hours} unit="hrs" sub={`${kpi.teachers_tracked} teachers`} color={C.indigo}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><CC title="Monthly absence rate" subtitle="Percentage per month" height={230}><canvas ref={r1}/></CC><CC title="Teacher attendance hours" subtitle="Total & avg per teacher" height={230}><canvas ref={r2}/></CC></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><CC title="Top most absent students" subtitle="Rose > 35% · amber 20–35% · teal < 20%" height={280}><canvas ref={r3}/></CC><CC title="Absence vs score scatter" subtitle="Rose = at-risk zone (absent + low score)" height={280}><canvas ref={r4}/></CC></div><IS color={C.rose} items={[{label:"Most absent",value:topAbs[0]?.student_name},{label:"Peak month",value:absMon.length?absMon.reduce((a,b)=>a.absence_rate>b.absence_rate?a:b).month_name:"—"},{label:"Teacher late rate",value:`${kpi.teacher_late_rate}%`},{label:"At-risk definition",value:"Absence > 20% + Score < 10"}]}/></div>);
}

// ── Axis 4 — Weather Impact ──────────────────────────────────────────────────
function Axis4({qs}){
  const[wData,setWData]=useState([]);const[rvd,setRvd]=useState(null);const[seas,setSeas]=useState([]);
  useEffect(()=>{Promise.all([apiFetch(`/axis4/weather-vs-absence${qs}`,"weatherVsAbsence"),apiFetch(`/axis4/rainy-vs-dry-summary${qs}`,"rainyVsDry"),apiFetch(`/axis4/seasonal-patterns${qs}`,"seasonal")]).then(([w,r,s])=>{setWData(w);setRvd(r);setSeas(s);});},[qs]);
  const r1=useRef(),r2=useRef(),r3=useRef();
  useChart(r1,{type:"scatter",data:{datasets:[{label:"Dry",data:wData.filter(d=>!d.is_rainy).map(d=>({x:d.precipitation_mm,y:d.absence_rate,date:d.full_date})),backgroundColor:`${C.sky}CC`,pointRadius:6},{label:"Rainy",data:wData.filter(d=>d.is_rainy).map(d=>({x:d.precipitation_mm,y:d.absence_rate,date:d.full_date})),backgroundColor:`${C.rose}CC`,pointRadius:6}]},options:{...CD,plugins:{...CD.plugins,tooltip:{...CD.plugins.tooltip,callbacks:{label:ctx=>[ctx.dataset.label,`Precip: ${ctx.raw.x}mm`,`Absence: ${ctx.raw.y}%`]}}},scales:{x:{...CD.scales.x,title:{display:true,text:"Precipitation (mm)",color:C.textMuted}},y:{...CD.scales.y,title:{display:true,text:"Absence rate (%)",color:C.textMuted}}}}});
  useChart(r2,{type:"bar",data:{labels:seas.map(d=>d.month_name),datasets:[{label:"Absence %",data:seas.map(d=>d.absence_rate),backgroundColor:`${C.rose}CC`,borderRadius:4,yAxisID:"y"},{label:"Precip mm",data:seas.map(d=>d.avg_precipitation||0),backgroundColor:`${C.sky}88`,borderRadius:4,yAxisID:"y2"}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,position:"left"},y2:{...CD.scales.y,position:"right",grid:{drawOnChartArea:false}}}}});
  useChart(r3,{type:"bar",data:{labels:["Rainy days","Dry days"],datasets:[{label:"Avg absence %",data:rvd?[rvd.rainy_avg,rvd.dry_avg]:[0,0],backgroundColor:[`${C.rose}CC`,`${C.sky}CC`],borderWidth:0,borderRadius:8}]},options:{...CD,plugins:{...CD.plugins,legend:{display:false}},scales:{x:{...CD.scales.x},y:{...CD.scales.y,min:0,ticks:{...CD.scales.y.ticks,callback:v=>`${v}%`}}}}});
  const sens=rvd&&rvd.rainy_avg&&rvd.dry_avg?(rvd.rainy_avg-rvd.dry_avg).toFixed(1):"—";
  return(<div style={{display:"flex",flexDirection:"column",gap:22}}><SH axis="A4" title="Contextual Analysis — Weather Impact" desc="Absence on rainy vs dry days · seasonal patterns · weather sensitivity · Open-Meteo data" color={C.sky}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><KpiCard label="Rainy-day absence avg" value={rvd?.rainy_avg} unit="%" color={C.rose}/><KpiCard label="Dry-day absence avg" value={rvd?.dry_avg} unit="%" color={C.sky}/><KpiCard label="Weather sensitivity" value={sens} unit="pts" sub="Rainy − dry delta" color={C.amber}/><KpiCard label="Rainy days tracked" value={rvd?.n_rainy} sub={`${rvd?.n_dry??0} dry days`} color={C.indigo}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><CC title="Precipitation vs absence — scatter" subtitle="Each dot = one school day · rose=rainy · blue=dry" height={260}><canvas ref={r1}/></CC><CC title="Rainy vs dry — direct comparison" subtitle="Mean absence rate by weather condition" height={260}><canvas ref={r3}/></CC></div><CC title="Seasonal patterns — absence & precipitation by month" subtitle="Rose bars = absence % · Blue bars = avg precipitation mm" height={260}><canvas ref={r2}/></CC><IS color={C.sky} items={[{label:"Weather sensitivity",value:`+${sens} pts on rainy days`},{label:"Rainiest month",value:seas.length?seas.reduce((a,b)=>(a.avg_precipitation||0)>(b.avg_precipitation||0)?a:b).month_name:"—"},{label:"Worst absence month",value:seas.length?seas.reduce((a,b)=>a.absence_rate>b.absence_rate?a:b).month_name:"—"},{label:"Data source",value:"Open-Meteo archive · Sousse"}]}/></div>);
}

// ── Axis 5 — Pedagogical Sessions ────────────────────────────────────────────
function Axis5({qs}){
  const[subjects,setSubjects]=useState([]);const[selSubj,setSelSubj]=useState("");const[outcomes,setOutcomes]=useState([]);const[disp,setDisp]=useState([]);const[pp,setPp]=useState([]);
  useEffect(()=>{apiFetch("/axis5/subject-list","subjectList").then(s=>{setSubjects(s);if(s[0])setSelSubj(s[0].subject||s[0]);});},[]);
  useEffect(()=>{const sq=selSubj?`${qs?qs+"&":"?"}subject=${encodeURIComponent(selSubj)}`:qs;Promise.all([apiFetch(`/axis5/outcomes-by-report${sq}`,"outcomesByReport"),apiFetch(`/axis5/dispersion-by-report${qs}`,"dispersion"),apiFetch(`/axis5/presence-performance-by-report${qs}`,"presencePerf")]).then(([o,d,p])=>{setOutcomes(o);setDisp(d);setPp(p);});},[qs,selSubj]);
  const r1=useRef(),r2=useRef(),r3=useRef();
  useChart(r1,{type:"bar",data:{labels:outcomes.map(d=>`${d.report_name}`),datasets:[{label:"Avg score",data:outcomes.map(d=>d.avg_score),backgroundColor:`${C.emerald}CC`,borderRadius:5,yAxisID:"y"},{label:"Pass %",data:outcomes.map(d=>d.pass_rate),backgroundColor:`${C.amber}88`,borderRadius:5,yAxisID:"y2"}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,max:20,position:"left"},y2:{...CD.scales.y,min:0,max:100,position:"right",grid:{drawOnChartArea:false}}}}});
  useChart(r2,{type:"bar",data:{labels:disp.map(d=>d.report_name),datasets:[{label:"Score range ± σ",data:disp.map(d=>[Math.max(0,d.score_avg-(d.score_stddev||0)),Math.min(20,d.score_avg+(d.score_stddev||0))]),backgroundColor:`${C.sky}66`,borderColor:C.sky,borderWidth:1,borderRadius:4}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,min:0,max:20}}}});
  useChart(r3,{type:"scatter",data:{datasets:[{data:pp.map(d=>({x:d.presence_rate,y:d.avg_score,name:d.report_name})),backgroundColor:`${C.emerald}CC`,pointRadius:8}]},options:{...CD,plugins:{...CD.plugins,legend:{display:false},tooltip:{...CD.plugins.tooltip,callbacks:{label:ctx=>[ctx.raw.name,`Presence: ${ctx.raw.x?.toFixed(1)}%`,`Score: ${ctx.raw.y?.toFixed(2)}/20`]}}},scales:{x:{...CD.scales.x,min:70,max:100,title:{display:true,text:"Presence rate (%)",color:C.textMuted}},y:{...CD.scales.y,min:0,max:20,title:{display:true,text:"Avg score /20",color:C.textMuted}}}}});
  return(<div style={{display:"flex",flexDirection:"column",gap:22}}><SH axis="A5" title="Pedagogical Session Analysis" desc="Outcomes per evaluation report · score dispersion · presence–performance correlation" color={C.emerald}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><KpiCard label="Evaluation reports" value={disp.length} color={C.emerald}/><KpiCard label="Best report avg" value={disp.length?Math.max(...disp.map(d=>d.score_avg)).toFixed(1):"—"} unit="/20" color={C.teal}/><KpiCard label="Highest dispersion" value={disp.length?Math.max(...disp.map(d=>d.score_stddev||0)).toFixed(2):"—"} unit=" σ" color={C.amber}/><KpiCard label="Subjects" value={subjects.length} color={C.indigo}/></div><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:12,color:C.textMuted}}>Subject:</span><select value={selSubj} onChange={e=>setSelSubj(e.target.value)} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:8,color:C.text,padding:"6px 12px",fontSize:12,outline:"none",cursor:"pointer"}}>{subjects.map((s,i)=><option key={i} value={s.subject||s}>{s.subject||s}</option>)}</select></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><CC title={`Outcomes by report — ${selSubj||"all"}`} subtitle="Avg score (green) vs pass rate % (amber)" height={240}><canvas ref={r1}/></CC><CC title="Score dispersion per report" subtitle="Bar = avg ± 1σ range" height={240}><canvas ref={r2}/></CC></div><CC title="Presence rate vs score per evaluation period" subtitle="Each dot = one report — does higher presence predict higher score?" height={260}><canvas ref={r3}/></CC><IS color={C.emerald} items={[{label:"Best period",value:disp.length?disp.reduce((a,b)=>a.score_avg>b.score_avg?a:b).report_name:"—"},{label:"Most volatile",value:disp.length?disp.reduce((a,b)=>(a.score_stddev||0)>(b.score_stddev||0)?a:b).report_name:"—"},{label:"Total evaluations",value:disp.reduce((s,d)=>s+(d.n||0),0).toLocaleString()},{label:"Subject in focus",value:selSubj||"All"}]}/></div>);
}

// ── Axis 6 — Academic Risk ───────────────────────────────────────────────────
function Axis6({qs}){
  const[scores,setScores]=useState([]);const[dist,setDist]=useState([]);const[warn,setWarn]=useState([]);
  useEffect(()=>{Promise.all([apiFetch(`/axis6/risk-scores${qs}`,"riskScores"),apiFetch(`/axis6/risk-distribution${qs}`,"riskDist"),apiFetch(`/axis6/early-warning-indicators${qs}`,"earlyWarning")]).then(([s,d,w])=>{setScores(s);setDist(d);setWarn(w);});},[qs]);
  const r1=useRef(),r2=useRef();
  const top15=scores.slice(0,15);
  useChart(r1,{type:"bar",data:{labels:top15.map(d=>d.student_name.split(" ")[0]),datasets:[{label:"Risk score",data:top15.map(d=>d.risk_score),backgroundColor:top15.map(d=>d.risk_level==="High"?`${C.rose}CC`:d.risk_level==="Medium"?`${C.amber}CC`:`${C.teal}CC`),borderWidth:0,borderRadius:5}]},options:{indexAxis:"y",...CD,plugins:{...CD.plugins,legend:{display:false},tooltip:{...CD.plugins.tooltip,callbacks:{label:ctx=>[` Risk: ${ctx.parsed.x}`,` Score: ${top15[ctx.dataIndex]?.avg_score}/20`,` Absence: ${top15[ctx.dataIndex]?.absence_rate}%`]}}},scales:{x:{...CD.scales.x,min:0,max:100},y:{...CD.scales.y}}}});
  useChart(r2,{type:"doughnut",data:{labels:dist.map(d=>d.risk_level),datasets:[{data:dist.map(d=>d.student_count),backgroundColor:[`${C.rose}CC`,`${C.amber}CC`,`${C.teal}CC`],borderWidth:2,borderColor:C.bg,hoverOffset:8}]},options:{...CD,cutout:"65%",plugins:{...CD.plugins,tooltip:{...CD.plugins.tooltip,callbacks:{label:ctx=>[` ${ctx.label}: ${ctx.parsed} students`,` Avg score: ${dist[ctx.dataIndex]?.avg_score}/20`]}}},scales:{x:{display:false},y:{display:false}}}});
  const highN=dist.find(d=>d.risk_level==="High")?.student_count||0;
  const medN=dist.find(d=>d.risk_level==="Medium")?.student_count||0;
  return(<div style={{display:"flex",flexDirection:"column",gap:22}}><SH axis="A6" title="Academic Risk Detection" desc="Composite risk score · early warning indicators · at-risk profiles · intervention prioritization" color={C.rose}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><KpiCard label="High-risk students" value={highN} color={C.rose} sub="Risk ≥ 60"/><KpiCard label="Medium-risk" value={medN} color={C.amber} sub="Risk 35–60"/><KpiCard label="Students analysed" value={dist.reduce((s,d)=>s+d.student_count,0)} color={C.teal}/><KpiCard label="3-flag warnings" value={warn.filter(w=>w.warning_count>=3).length} color={C.violet} sub="Need immediate action"/></div><div style={{display:"grid",gridTemplateColumns:"2fr 1fr",gap:16}}><CC title="Risk score — top 15 at-risk students" subtitle="Rose=high · amber=medium · teal=low" height={340}><canvas ref={r1}/></CC><CC title="Risk level distribution" subtitle="All students with sufficient data" height={340}><canvas ref={r2}/><div style={{textAlign:"center",marginTop:-160,pointerEvents:"none"}}><div style={{fontSize:22,fontWeight:700,color:C.rose,fontFamily:"'Space Mono',monospace"}}>{highN}</div><div style={{fontSize:11,color:C.textMuted}}>high risk</div></div></CC></div>
  <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,overflow:"hidden"}}><div style={{padding:"16px 20px",borderBottom:`1px solid ${C.border}`,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:13,fontWeight:600,color:C.text}}>Early warning indicators</div><div style={{fontSize:11,color:C.textMuted,marginTop:2}}>Students with ≥ 2 active risk flags — prioritize for intervention</div></div><span style={{background:`${C.rose}18`,color:C.rose,border:`1px solid ${C.rose}40`,borderRadius:20,padding:"3px 12px",fontSize:11,fontWeight:600}}>{warn.length} students</span></div>
  <div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:`${C.border}40`}}>{["Student","Avg score","Absence %","Fail rate","Low score","High absence","High fail","Flags","Risk"].map(h=><th key={h} style={{padding:"10px 16px",textAlign:"left",color:C.textMuted,fontWeight:500,whiteSpace:"nowrap"}}>{h}</th>)}</tr></thead><tbody>{warn.map((w,i)=>(<tr key={i} style={{borderTop:`1px solid ${C.border}`,background:i%2===0?"transparent":`${C.card}80`}}><td style={{padding:"10px 16px",color:C.text,fontWeight:500}}>{w.student_name}</td><td style={{padding:"10px 16px",color:w.avg_score<10?C.rose:C.amber,fontFamily:"'Space Mono',monospace"}}>{w.avg_score?.toFixed(1)}</td><td style={{padding:"10px 16px",color:w.absence_rate>20?C.rose:C.textMuted,fontFamily:"'Space Mono',monospace"}}>{w.absence_rate?.toFixed(1)}%</td><td style={{padding:"10px 16px",color:w.fail_rate_pct>50?C.rose:C.textMuted,fontFamily:"'Space Mono',monospace"}}>{w.fail_rate_pct?.toFixed(1)}%</td><td style={{padding:"10px 16px",textAlign:"center"}}>{w.flag_low_score?<span style={{color:C.rose}}>●</span>:<span style={{color:C.border}}>○</span>}</td><td style={{padding:"10px 16px",textAlign:"center"}}>{w.flag_high_absence?<span style={{color:C.rose}}>●</span>:<span style={{color:C.border}}>○</span>}</td><td style={{padding:"10px 16px",textAlign:"center"}}>{w.flag_high_fail_rate?<span style={{color:C.rose}}>●</span>:<span style={{color:C.border}}>○</span>}</td><td style={{padding:"10px 16px",textAlign:"center"}}><span style={{fontFamily:"'Space Mono',monospace",fontWeight:700,color:w.warning_count>=3?C.rose:C.amber}}>{w.warning_count}/3</span></td><td style={{padding:"10px 16px"}}><RB level={w.warning_count>=3?"High":"Medium"}/></td></tr>))}</tbody></table></div></div>
  <IS color={C.rose} items={[{label:"Highest risk",value:scores[0]?.student_name},{label:"Formula",value:"Acad 40% + Absence 35% + Fail 25%"},{label:"High threshold",value:"Risk score ≥ 60"},{label:"3-flag students",value:`${warn.filter(w=>w.warning_count>=3).length} need immediate action`}]}/></div>);
}

// ── Axis 7 — Geographic Distribution ────────────────────────────────────────
function Axis7({qs}){
  const[zones,setZones]=useState([]);
  useEffect(()=>{apiFetch(`/axis7/students-by-zone${qs}`,"zones").then(setZones);},[qs]);
  const r1=useRef();
  useChart(r1,{type:"bar",data:{labels:zones.map(z=>z.zone_name),datasets:[{label:"Student count",data:zones.map(z=>z.student_count),backgroundColor:`${C.indigo}CC`,borderRadius:5,yAxisID:"y"},{label:"Absence %",data:zones.map(z=>z.absence_rate),backgroundColor:`${C.rose}CC`,borderRadius:5,yAxisID:"y2"}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,position:"left"},y2:{...CD.scales.y,position:"right",grid:{drawOnChartArea:false},ticks:{...CD.scales.y.ticks,callback:v=>`${v}%`}}}}});
  return(<div style={{display:"flex",flexDirection:"column",gap:22}}><SH axis="A7" title="Geographic Distribution" desc="Student distribution, absence & late rates by zone" color={C.indigo}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><KpiCard label="Total zones" value={zones.length} color={C.indigo}/><KpiCard label="Total students" value={zones.reduce((s,z)=>s+z.student_count,0)} color={C.teal}/><KpiCard label="Avg absence rate" value={zones.length?(zones.reduce((s,z)=>s+z.absence_rate,0)/zones.length).toFixed(1):0} unit="%" color={C.rose}/><KpiCard label="Top zone" value={zones.length?zones.reduce((a,b)=>a.student_count>b.student_count?a:b).zone_name:"—"} color={C.amber}/></div><CC title="Students per zone" subtitle="Blue bars: student count · Red bars: absence rate" height={300}><canvas ref={r1}/></CC><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:`${C.border}40`}}>{["Zone","Students","Absence %","Late %","Avg Score"].map(h=><th key={h} style={{padding:"10px 16px",textAlign:"left",color:C.textMuted}}>{h}</th>)}</tr></thead><tbody>{zones.map((z,i)=>(<tr key={i} style={{borderTop:`1px solid ${C.border}`}}><td style={{padding:"10px 16px",color:C.text}}>{z.zone_name}</td><td style={{padding:"10px 16px",fontFamily:"'Space Mono',monospace"}}>{z.student_count}</td><td style={{padding:"10px 16px",color:z.absence_rate>10?C.rose:C.teal}}>{z.absence_rate?.toFixed(1)}%</td><td style={{padding:"10px 16px",color:z.late_rate>5?C.amber:C.textMuted}}>{z.late_rate?.toFixed(1)}%</td><td style={{padding:"10px 16px",color:z.avg_score>=12?C.teal:C.amber}}>{z.avg_score?.toFixed(1)}/20</td></tr>))}</tbody></table></div></div>);
}

// ── Axis 8 — Holiday & Exam Period Impact ────────────────────────────────────
function Axis8({qs}){
  const[periods,setPeriods]=useState([]);
  useEffect(()=>{apiFetch(`/axis8/absence-by-period-type${qs}`,"periodTypes").then(setPeriods);},[qs]);
  const r1=useRef();
  useChart(r1,{type:"bar",data:{labels:periods.map(p=>p.period_label),datasets:[{label:"Avg absence rate",data:periods.map(p=>p.avg_absence_rate),backgroundColor:periods.map(p=>p.period_type==="exam"?`${C.teal}CC`:p.period_type==="pre_exam"?`${C.amber}CC`:`${C.rose}CC`),borderRadius:5}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,min:0,ticks:{...CD.scales.y.ticks,callback:v=>`${v}%`}}}}});
  const maxPeriod=periods.length?periods.reduce((a,b)=>a.avg_absence_rate>b.avg_absence_rate?a:b):null;
  const minPeriod=periods.length?periods.reduce((a,b)=>a.avg_absence_rate<b.avg_absence_rate?a:b):null;
  return(<div style={{display:"flex",flexDirection:"column",gap:22}}><SH axis="A8" title="Holiday & Exam Period Analysis" desc="Absence rates before/after holidays and during exam periods" color={C.orange}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><KpiCard label="Period types" value={periods.length} color={C.orange}/><KpiCard label="Highest absence" value={maxPeriod?.avg_absence_rate??0} unit="%" sub={maxPeriod?.period_label} color={C.rose}/><KpiCard label="Lowest absence" value={minPeriod?.avg_absence_rate??0} unit="%" sub={minPeriod?.period_label} color={C.teal}/><KpiCard label="Days analyzed" value={periods.reduce((s,p)=>s+(p.n_days||0),0)} color={C.indigo}/></div><CC title="Absence rate by period type" subtitle="Teal = exam periods · amber = pre-exam · rose = holiday-adjacent" height={320}><canvas ref={r1}/></CC><div style={{display:"grid",gridTemplateColumns:"repeat(5,1fr)",gap:12}}>{periods.map((p,i)=>(<div key={i} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:12,padding:"14px 16px",borderTop:`3px solid ${p.period_type==="exam"?C.teal:p.period_type==="pre_exam"?C.amber:C.rose}`}}><div style={{fontSize:10,color:C.textMuted,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>{p.period_label}</div><div style={{fontSize:22,fontWeight:700,fontFamily:"'Space Mono',monospace",color:p.period_type==="exam"?C.teal:p.period_type==="pre_exam"?C.amber:C.rose}}>{p.avg_absence_rate}%</div><div style={{fontSize:11,color:C.textMuted,marginTop:4}}>{p.n_days} days</div></div>))}</div></div>);
}

// ── Axis 9 — Prep School Origin ──────────────────────────────────────────────
function Axis9({qs}){
  const[schools,setSchools]=useState([]);
  useEffect(()=>{apiFetch(`/axis9/performance-by-school${qs}`,"schools").then(setSchools);},[qs]);
  const r1=useRef();
  const top10=schools.slice(0,10);
  useChart(r1,{type:"bar",data:{labels:top10.map(s=>s.school_name.length>15?s.school_name.slice(0,13)+"…":s.school_name),datasets:[{label:"Avg score",data:top10.map(s=>s.avg_score),backgroundColor:`${C.emerald}CC`,borderRadius:5,yAxisID:"y"},{label:"Pass %",data:top10.map(s=>s.pass_rate),backgroundColor:`${C.amber}88`,borderRadius:5,yAxisID:"y2"}]},options:{...CD,scales:{x:{...CD.scales.x},y:{...CD.scales.y,min:0,max:20,position:"left"},y2:{...CD.scales.y,min:0,max:100,position:"right",grid:{drawOnChartArea:false},ticks:{...CD.scales.y.ticks,callback:v=>`${v}%`}}}}});
  const best=schools.length?schools.reduce((a,b)=>(a.avg_score||0)>(b.avg_score||0)?a:b):null;
  return(<div style={{display:"flex",flexDirection:"column",gap:22}}><SH axis="A9" title="Previous School Performance" desc="How students from different prep schools perform in our institution" color={C.emerald}/><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:14}}><KpiCard label="Schools tracked" value={schools.length} color={C.emerald}/><KpiCard label="Best school avg" value={best?.avg_score??0} unit="/20" sub={best?.school_name} color={C.teal}/><KpiCard label="Top pass rate" value={schools.length?Math.max(...schools.map(s=>s.pass_rate||0)).toFixed(1):0} unit="%" color={C.amber}/><KpiCard label="Total students" value={schools.reduce((s,sc)=>s+(sc.student_count||0),0)} color={C.indigo}/></div><CC title="Top schools by average score" subtitle="Green: avg score /20 · Amber: pass rate %" height={300}><canvas ref={r1}/></CC><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:`${C.border}40`}}>{["Previous School","Students","Avg Score","Pass Rate","Absence Rate"].map(h=><th key={h} style={{padding:"10px 16px",textAlign:"left",color:C.textMuted}}>{h}</th>)}</tr></thead><tbody>{schools.map((s,i)=>(<tr key={i} style={{borderTop:`1px solid ${C.border}`}}><td style={{padding:"10px 16px",color:C.text}}>{s.school_name}</td><td style={{padding:"10px 16px",fontFamily:"'Space Mono',monospace"}}>{s.student_count}</td><td style={{padding:"10px 16px",color:(s.avg_score||0)>=12?C.teal:C.amber,fontFamily:"'Space Mono',monospace"}}>{s.avg_score?.toFixed(1)??'—'}/20</td><td style={{padding:"10px 16px",color:(s.pass_rate||0)>=70?C.teal:C.amber,fontFamily:"'Space Mono',monospace"}}>{s.pass_rate?.toFixed(1)??'—'}%</td><td style={{padding:"10px 16px",color:(s.absence_rate||0)>10?C.rose:C.textMuted,fontFamily:"'Space Mono',monospace"}}>{s.absence_rate?.toFixed(1)??'—'}%</td></tr>))}</tbody></table></div></div>);
}

// ── Navigation config ────────────────────────────────────────────────────────
const AXES=[
  {id:"axis1",label:"A1 — Academic",color:C.teal},
  {id:"axis2",label:"A2 — Trends",color:C.violet},
  {id:"axis3",label:"A3 — Attendance",color:C.rose},
  {id:"axis4",label:"A4 — Weather",color:C.sky},
  {id:"axis5",label:"A5 — Sessions",color:C.emerald},
  {id:"axis6",label:"A6 — Risk",color:C.amber},
  {id:"axis7",label:"A7 — Geography",color:C.indigo},
  {id:"axis8",label:"A8 — Holiday Impact",color:C.orange},
  {id:"axis9",label:"A9 — Prep Schools",color:C.emerald},
];

// ── Root Dashboard ───────────────────────────────────────────────────────────
export default function Dashboard(){
  const[axis,setAxis]=useState("axis1");
  const[yearKey,setYearKey]=useState("7");
  const[years,setYears]=useState(M.schoolYears);

  useEffect(()=>{
    apiFetch("/school-years","schoolYears").then(y=>{
      setYears(y);
      const c=y.find(x=>x.IsCurrent);
      if(c) setYearKey(String(c.SchoolYearKey));
    });
  },[]);

  const qs=yearKey?`?school_year_key=${yearKey}`:"";
  const ac=AXES.find(a=>a.id===axis)?.color||C.teal;

  return(
    <div style={{minHeight:"100vh",background:C.bg,color:C.text,fontFamily:"'DM Sans',sans-serif",paddingBottom:48}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Mono:wght@400;700&display=swap');*{box-sizing:border-box}::-webkit-scrollbar{width:5px;background:${C.bg}}::-webkit-scrollbar-thumb{background:${C.border};border-radius:3px}select option{background:${C.card}}table tr:hover{background:${C.cardHover}!important}`}</style>

      {/* Header */}
      <div style={{background:`${C.card}F2`,backdropFilter:"blur(16px)",borderBottom:`1px solid ${C.border}`,padding:"0 36px",position:"sticky",top:0,zIndex:100}}>
        <div style={{maxWidth:1300,margin:"0 auto",display:"flex",alignItems:"center",justifyContent:"space-between",height:62,gap:12,flexWrap:"wrap"}}>
          {/* Logo */}
          <div style={{display:"flex",alignItems:"center",gap:10,flexShrink:0}}>
            <div style={{width:34,height:34,borderRadius:9,background:`linear-gradient(135deg,${C.teal},${C.indigo})`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:700,color:"#0F172A",fontFamily:"'Space Mono',monospace"}}>E</div>
            <div>
              <div style={{fontSize:15,fontWeight:700,letterSpacing:"-0.3px"}}>Educated BI</div>
              <div style={{fontSize:10,color:C.textMuted,marginTop:-1}}>Intelligent Analytics Platform</div>
            </div>
          </div>

          {/* Axis nav */}
          <div style={{display:"flex",gap:6,flexWrap:"wrap",justifyContent:"center"}}>
            {AXES.map(({id,label,color})=>(
              <button key={id} onClick={()=>setAxis(id)} style={{background:axis===id?`${color}18`:"transparent",border:`1px solid ${axis===id?color:C.border}`,borderRadius:8,padding:"6px 12px",cursor:"pointer",color:axis===id?color:C.textMuted,fontSize:11,fontWeight:axis===id?600:400,transition:"all .15s"}}>{label}</button>
            ))}
          </div>

          {/* Year selector */}
          <div style={{display:"flex",alignItems:"center",gap:8,flexShrink:0}}>
            <span style={{fontSize:11,color:C.textMuted}}>Year</span>
            <select value={yearKey} onChange={e=>setYearKey(e.target.value)} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:7,color:C.text,padding:"5px 10px",fontSize:12,outline:"none",cursor:"pointer"}}>
              <option value="">All</option>
              {years.map(y=>(
                <option key={y.SchoolYearKey} value={String(y.SchoolYearKey)}>
                  {y.YearLabel}{y.IsCurrent?" ★":""}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Accent line */}
      <div style={{height:2,background:`linear-gradient(90deg,${ac},${ac}40,transparent)`,transition:"background 0.3s"}}/>

      {/* Content */}
      <div style={{maxWidth:1300,margin:"0 auto",padding:"28px 36px"}}>
        {axis==="axis1"&&<Axis1 qs={qs}/>}
        {axis==="axis2"&&<Axis2 qs={qs}/>}
        {axis==="axis3"&&<Axis3 qs={qs}/>}
        {axis==="axis4"&&<Axis4 qs={qs}/>}
        {axis==="axis5"&&<Axis5 qs={qs}/>}
        {axis==="axis6"&&<Axis6 qs={qs}/>}
        {axis==="axis7"&&<Axis7 qs={qs}/>}
        {axis==="axis8"&&<Axis8 qs={qs}/>}
        {axis==="axis9"&&<Axis9 qs={qs}/>}
      </div>
    </div>
  );
}